# Generated by Django 4.2.21 on 2025-05-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trackableurgency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackableClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
