# Generated by Django 4.2.21 on 2025-07-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_event_options_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackablestatus',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
