# Generated by Django 4.2.21 on 2025-07-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
