# Generated by Django 4.2.21 on 2025-07-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprints', '0002_sprint_is_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['planned_start_date']},
        ),
    ]
