# Generated by Django 4.2.21 on 2025-07-17 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_trackablestatus_name'),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_user_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstory',
            name='status',
            field=models.ForeignKey(default=stories.models.get_default_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackablestatus'),
        ),
    ]
