# Generated by Django 4.2.21 on 2025-07-17 14:17

from django.db import migrations, models
import django.db.models.deletion
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trackablestatus_name'),
        ('stories', '0002_userstory_assignees_userstory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='urgency',
            field=models.ForeignKey(default=stories.models.get_default_urgency, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackableurgency'),
        ),
    ]
