# Generated by Django 4.2.21 on 2025-07-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_userstory_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='status',
            field=models.CharField(blank=True, default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
