# Generated by Django 4.2.21 on 2025-07-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_alter_userstory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='assignees',
        ),
        migrations.AddField(
            model_name='userstory',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
