# Generated by Django 4.2.21 on 2025-07-09 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.TextField()),
                ('category', models.CharField(choices=[('docker', 'Docker'), ('k8s', 'Kubernetes'), ('bash', 'Bash'), ('deploy', 'Deployment'), ('other', 'Other')], default='other', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
