# Generated by Django 4.2.21 on 2025-07-18 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0002_remove_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
