# Generated by Django 4.2.21 on 2025-07-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
