# Generated by Django 4.2.21 on 2025-07-21 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0004_assignment_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignees',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('business', 'Business Analysis'), ('development', 'Development'), ('quality', 'QA'), ('bug-fixing', 'Bug fixing'), ('deployment', 'Deployment')], default='business', max_length=20),
        ),
    ]
