# Generated by Django 4.2.21 on 2025-07-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignment_assignees_assignment_assignee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
