# Generated by Django 4.2.21 on 2025-08-03 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_assignment_options_assignment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='completion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Completion percentage (0–100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
