# Generated by Django 4.2.21 on 2025-05-26 23:54

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trackableurgency'),
        ('tasks', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default=tasks.models.get_default_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackablestatus'),
        ),
    ]
