# Generated by Django 4.2.21 on 2025-05-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
