# Generated by Django 4.2.21 on 2025-06-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_task_public_task_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
