# Generated by Django 4.2.21 on 2025-07-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('tasks', '0012_remove_task_assignee_task_assignees'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='stories.userstory'),
        ),
    ]
