# Generated by Django 4.2.21 on 2025-07-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_trackablestatus_name'),
        ('tasks', '0013_task_user_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='classification',
            field=models.ForeignKey(blank=True, default=tasks.models.get_default_classification, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackableclassification'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, default=tasks.models.get_default_status, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackablestatus'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.ForeignKey(blank=True, default=tasks.models.get_default_urgency, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trackableurgency'),
        ),
        migrations.AlterField(
            model_name='task',
            name='visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, null=True),
        ),
    ]
