# Generated by Django 4.2.21 on 2025-07-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task', 'Task'), ('comment', 'Comment'), ('reminder', 'Reminder'), ('custom', 'Custom')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
